### DISCUSSION TITLE
How can I remove this icon?

### DISCUSSION THREAD

**Discussion by luishiguera** [TarekRaafat/autoComplete.js#304] [Q&A] [answered]
Hello, this icon will appear when hovering over the input

![image](https://user-images.githubusercontent.com/43837730/146659252-efd34b30-c93a-4d46-9f6b-c7888fbc60a5.png)

**Comment by folknor** [comment, marked as answer]
That's not added by autoComplete.js.

https://www.google.com/search?q=css+remove+x+icon+in+input

```css
/* clears the ‘X’ from Internet Explorer */
input[type=search]::-ms-clear { display: none; width : 0; height: 0; }
input[type=search]::-ms-reveal { display: none; width : 0; height: 0; }

/* clears the ‘X’ from Chrome */
input[type="search"]::-webkit-search-decoration,
input[type="search"]::-webkit-search-cancel-button,
input[type="search"]::-webkit-search-results-button,
input[type="search"]::-webkit-search-results-decoration { display: none; }
```
