### ISSUE TITLE
Have the ability to use another tag than "mark" for highlight of matched characters

### ISSUE THREAD

**Issue by williamdes** [TarekRaafat/autoComplete.js#306]
**Is your feature request related to a problem? Please describe.**
I would like to not use "mark" as it has bootstrap classes and use another tag like "b"

**Please Describe alternatives you've considered**
Override the bootstrap CSS

**Additional context**
Refactoring at https://github.com/code-lts/doctum

PS:  this lib is great !

**Comment by folknor** [comment]
This is the only CSS for `mark` added by bootstrap 5's CSS reboot stylesheet:
```scss
mark {
  padding: $mark-padding;
  background-color: $mark-bg;
}
```

In your CSS, if you do this:
```css
#autoComplete mark {
  padding: 0;
  background-color: none;
}
```
You should be fine, because `#autoComplete mark` has a specificity of 101, while `mark` only has 001.

https://polypane.app/css-specificity-calculator/

There's more talk about this specific topic here https://github.com/TarekRaafat/autoComplete.js/issues/264
